# openapi2-functions.yaml
swagger: '2.0'
info:
  title: apple
  description: API created to view the Moisaic APP download report on IOS
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /downloads:
    get:
      summary: API created to view the Moisaic APP download report on IOS
      operationId: apple-downloads
      x-google-backend:
        address: https://us-east4-mosaic-fertilizantes.cloudfunctions.net/apple-downloads
      security:
      - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
securityDefinitions:
  # This section configures basic authentication with an API key.
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"